// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcqz3ITuQx9-E2J-jxwABcFjCnkKWvaxU',
    appId: '1:978347682385:web:eaa4d387bd2f73d662e670',
    messagingSenderId: '978347682385',
    projectId: 'summonsviewer',
    authDomain: 'summonsviewer.firebaseapp.com',
    storageBucket: 'summonsviewer.firebasestorage.app',
    measurementId: 'G-VZS85H401S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCifIJFOidDXkGzDEMZk688ni0ovmXHkLk',
    appId: '1:978347682385:android:f3dbce02c86da1ec62e670',
    messagingSenderId: '978347682385',
    projectId: 'summonsviewer',
    storageBucket: 'summonsviewer.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcqz3ITuQx9-E2J-jxwABcFjCnkKWvaxU',
    appId: '1:978347682385:web:f665478b75e587b662e670',
    messagingSenderId: '978347682385',
    projectId: 'summonsviewer',
    authDomain: 'summonsviewer.firebaseapp.com',
    storageBucket: 'summonsviewer.firebasestorage.app',
    measurementId: 'G-6G26SRPYEV',
  );
}
